### ISSUE TITLE
learned_weighting_loss

### ISSUE THREAD

**Issue by bhack** [GrumpyZhou/visloc-apr#1]
Is `learned_weighting_loss` going to be negative? 
https://github.com/GrumpyZhou/visloc-apr/blob/master/networks/base/basenet.py#L121

**Comment by GrumpyZhou** [comment]
Hi @bhack,

Yes, using learned weighting loss, the loss value could go below 0.

**Comment by bhack** [comment]
Have you tried any formulation that maintain the loss > 0?

**Comment by GrumpyZhou** [comment]
Hi @bhack,

Yes, so i did naively using a hyper-parameter beta (>0) that weighting the positional and rotational, this should give always positive loss.

**Comment by bhack** [comment]
Yes
