### ISSUE TITLE
The link of Cambridge Landmarks Dataset is invalid, can you share with me the dataset you downloaded?

### ISSUE THREAD

**Issue by zhuixunforever** [GrumpyZhou/visloc-apr#3]
The link of [Cambridge Landmarks Dataset](http://mi.eng.cam.ac.uk/projects/relocalisation/#dataset) is invalid, can you share with me the dataset you downloaded?

**Comment by GrumpyZhou** [comment]
Hi ,

I am sorry that i am not responsible for maintaining the original Cambridge Landmarks dataset. I think the best way is to contact the author who released them.

**Comment by zhuixunforever** [comment]
That's all right, thank you for your reply. I'll contact the author.

**Comment by tsattler** [comment]
The Cambridge Landmarks dataset is still publicly available, just the original project page seems to be down.
Here are the links to the datasets:
Old Hospital: https://www.repository.cam.ac.uk/handle/1810/251342
Kings College: https://www.repository.cam.ac.uk/handle/1810/251342
St. Marys Church: https://www.repository.cam.ac.uk/handle/1810/251294
Great Court: https://www.repository.cam.ac.uk/handle/1810/251291
Shop Facade: https://www.repository.cam.ac.uk/handle/1810/251336
Street: https://www.repository.cam.ac.uk/handle/1810/251292

**Comment by zhuixunforever** [comment]
Fantastic! Thanks for your answer.

**Comment by zhuixunforever** [comment]
The Old Hospital should be: https://www.repository.cam.ac.uk/handle/1810/251340

**Comment by Dong-prog** [comment]
> The Old Hospital should be: https://www.repository.cam.ac.uk/handle/1810/251340

This is also invalid now. Could you share me with your Cambridge Landmarks Dataset? 
I would appreciate it if so!

**Comment by tsattler** [comment]
The link works perfectly fine for me.

**Comment by RebekkaBaertheleTHWS** [comment]
I can't reach any of the links above at the moment- does somebody know where I can download the dataset right now? @tsattler

**Comment by ussaema** [comment]
The links no longer work.

**Comment by Skorpinakos** [comment]
503 Service Unavailable

**Comment by tsattler** [comment]
We are not hosting the Cambridge Landmarks dataset. Please contact the authors of the dataset to ask about it.

**Comment by Skorpinakos** [comment]
since the issue is reoccurring and the authors don't really reply and multiple people end up here looking for it I will add my contact here for anyone needing it in the future while the official repository is out of service. ioannis.tsampras@ac.upatras.gr

**Comment by LuoXubo** [comment]
Do we need to download all of these sequences? Or just part of them is okay?
